# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SnakeIsland.ui'
#
# Created: Tue Apr 26 12:05:50 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 793)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.imageGroupBox.setGeometry(QtCore.QRect(10, 0, 391, 81))
        self.imageGroupBox.setObjectName("imageGroupBox")
        self.openImageButton = QtGui.QPushButton(self.imageGroupBox)
        self.openImageButton.setGeometry(QtCore.QRect(10, 20, 100, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openImageButton.sizePolicy().hasHeightForWidth())
        self.openImageButton.setSizePolicy(sizePolicy)
        self.openImageButton.setObjectName("openImageButton")
        self.imageNameLabel = QtGui.QLabel(self.imageGroupBox)
        self.imageNameLabel.setGeometry(QtCore.QRect(110, 30, 110, 17))
        self.imageNameLabel.setObjectName("imageNameLabel")
        self.brightnessDial = QtGui.QDial(self.imageGroupBox)
        self.brightnessDial.setGeometry(QtCore.QRect(90, 50, 31, 31))
        self.brightnessDial.setObjectName("brightnessDial")
        self.brightnessLabel = QtGui.QLabel(self.imageGroupBox)
        self.brightnessLabel.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.brightnessValueLabel = QtGui.QLabel(self.imageGroupBox)
        self.brightnessValueLabel.setGeometry(QtCore.QRect(130, 60, 81, 17))
        self.brightnessValueLabel.setObjectName("brightnessValueLabel")
        self.snakeGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.snakeGroupBox.setGeometry(QtCore.QRect(10, 330, 391, 331))
        self.snakeGroupBox.setObjectName("snakeGroupBox")
        self.resetSnakeButton = QtGui.QPushButton(self.snakeGroupBox)
        self.resetSnakeButton.setGeometry(QtCore.QRect(10, 45, 96, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetSnakeButton.sizePolicy().hasHeightForWidth())
        self.resetSnakeButton.setSizePolicy(sizePolicy)
        self.resetSnakeButton.setObjectName("resetSnakeButton")
        self.energyGroupBox = QtGui.QGroupBox(self.snakeGroupBox)
        self.energyGroupBox.setGeometry(QtCore.QRect(0, 180, 201, 156))
        self.energyGroupBox.setFlat(False)
        self.energyGroupBox.setCheckable(False)
        self.energyGroupBox.setObjectName("energyGroupBox")
        self.internalEnergyLabel = QtGui.QLabel(self.energyGroupBox)
        self.internalEnergyLabel.setGeometry(QtCore.QRect(10, 20, 51, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.internalEnergyLabel.sizePolicy().hasHeightForWidth())
        self.internalEnergyLabel.setSizePolicy(sizePolicy)
        self.internalEnergyLabel.setObjectName("internalEnergyLabel")
        self.spacingLabel = QtGui.QLabel(self.energyGroupBox)
        self.spacingLabel.setGeometry(QtCore.QRect(30, 70, 61, 17))
        self.spacingLabel.setObjectName("spacingLabel")
        self.curvatureLabel = QtGui.QLabel(self.energyGroupBox)
        self.curvatureLabel.setGeometry(QtCore.QRect(30, 90, 71, 17))
        self.curvatureLabel.setObjectName("curvatureLabel")
        self.goalLengthEdit = QtGui.QLineEdit(self.energyGroupBox)
        self.goalLengthEdit.setGeometry(QtCore.QRect(120, 40, 81, 21))
        self.goalLengthEdit.setObjectName("goalLengthEdit")
        self.goalLengthLabel = QtGui.QLabel(self.energyGroupBox)
        self.goalLengthLabel.setGeometry(QtCore.QRect(30, 40, 81, 17))
        self.goalLengthLabel.setObjectName("goalLengthLabel")
        self.externalEnergyLabel = QtGui.QLabel(self.energyGroupBox)
        self.externalEnergyLabel.setGeometry(QtCore.QRect(10, 130, 61, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.externalEnergyLabel.sizePolicy().hasHeightForWidth())
        self.externalEnergyLabel.setSizePolicy(sizePolicy)
        self.externalEnergyLabel.setObjectName("externalEnergyLabel")
        self.spacingDisplayLabel = QtGui.QLabel(self.energyGroupBox)
        self.spacingDisplayLabel.setGeometry(QtCore.QRect(120, 70, 121, 17))
        self.spacingDisplayLabel.setObjectName("spacingDisplayLabel")
        self.curvatureDisplayLabel = QtGui.QLabel(self.energyGroupBox)
        self.curvatureDisplayLabel.setGeometry(QtCore.QRect(120, 90, 121, 17))
        self.curvatureDisplayLabel.setObjectName("curvatureDisplayLabel")
        self.gradMagnDisplayLabel = QtGui.QLabel(self.energyGroupBox)
        self.gradMagnDisplayLabel.setGeometry(QtCore.QRect(120, 160, 121, 17))
        self.gradMagnDisplayLabel.setObjectName("gradMagnDisplayLabel")
        self.externalMaxLabel = QtGui.QLabel(self.energyGroupBox)
        self.externalMaxLabel.setGeometry(QtCore.QRect(70, 190, 31, 21))
        self.externalMaxLabel.setObjectName("externalMaxLabel")
        self.externalMaxDisplayLabel = QtGui.QLabel(self.energyGroupBox)
        self.externalMaxDisplayLabel.setGeometry(QtCore.QRect(120, 190, 91, 21))
        self.externalMaxDisplayLabel.setObjectName("externalMaxDisplayLabel")
        self.externalEnergyComboBox = QtGui.QComboBox(self.energyGroupBox)
        self.externalEnergyComboBox.setGeometry(QtCore.QRect(20, 160, 85, 21))
        self.externalEnergyComboBox.setObjectName("externalEnergyComboBox")
        self.innerWeightEdit = QtGui.QLineEdit(self.energyGroupBox)
        self.innerWeightEdit.setGeometry(QtCore.QRect(70, 20, 51, 20))
        self.innerWeightEdit.setObjectName("innerWeightEdit")
        self.outerWeightEdit = QtGui.QLineEdit(self.energyGroupBox)
        self.outerWeightEdit.setGeometry(QtCore.QRect(70, 130, 51, 20))
        self.outerWeightEdit.setObjectName("outerWeightEdit")
        self.flipNormalsButton = QtGui.QPushButton(self.snakeGroupBox)
        self.flipNormalsButton.setGeometry(QtCore.QRect(10, 70, 96, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flipNormalsButton.sizePolicy().hasHeightForWidth())
        self.flipNormalsButton.setSizePolicy(sizePolicy)
        self.flipNormalsButton.setObjectName("flipNormalsButton")
        self.snakeFromS57CheckBox = QtGui.QCheckBox(self.snakeGroupBox)
        self.snakeFromS57CheckBox.setGeometry(QtCore.QRect(115, 20, 131, 22))
        self.snakeFromS57CheckBox.setObjectName("snakeFromS57CheckBox")
        self.groupBox = QtGui.QGroupBox(self.snakeGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(0, 100, 381, 81))
        self.groupBox.setObjectName("groupBox")
        self.optimizationSlider = QtGui.QSlider(self.groupBox)
        self.optimizationSlider.setGeometry(QtCore.QRect(0, 50, 381, 29))
        self.optimizationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.optimizationSlider.setObjectName("optimizationSlider")
        self.optimizationStepsLabel = QtGui.QLabel(self.groupBox)
        self.optimizationStepsLabel.setGeometry(QtCore.QRect(10, 25, 46, 21))
        self.optimizationStepsLabel.setObjectName("optimizationStepsLabel")
        self.optimizationStepsEdit = QtGui.QLineEdit(self.groupBox)
        self.optimizationStepsEdit.setGeometry(QtCore.QRect(55, 25, 46, 21))
        self.optimizationStepsEdit.setObjectName("optimizationStepsEdit")
        self.optimizeButton = QtGui.QPushButton(self.groupBox)
        self.optimizeButton.setGeometry(QtCore.QRect(275, 20, 106, 27))
        self.optimizeButton.setObjectName("optimizeButton")
        self.fixedStepSizeCheckBox = QtGui.QCheckBox(self.groupBox)
        self.fixedStepSizeCheckBox.setGeometry(QtCore.QRect(105, 20, 126, 31))
        self.fixedStepSizeCheckBox.setObjectName("fixedStepSizeCheckBox")
        self.fixedStepSizeEdit = QtGui.QLineEdit(self.groupBox)
        self.fixedStepSizeEdit.setGeometry(QtCore.QRect(235, 25, 36, 21))
        self.fixedStepSizeEdit.setObjectName("fixedStepSizeEdit")
        self.resetMapSamplesButton = QtGui.QPushButton(self.snakeGroupBox)
        self.resetMapSamplesButton.setGeometry(QtCore.QRect(115, 70, 136, 27))
        self.resetMapSamplesButton.setObjectName("resetMapSamplesButton")
        self.reSampleS57Button = QtGui.QPushButton(self.snakeGroupBox)
        self.reSampleS57Button.setGeometry(QtCore.QRect(115, 45, 136, 26))
        self.reSampleS57Button.setObjectName("reSampleS57Button")
        self.hideReferenceCheckBox = QtGui.QCheckBox(self.snakeGroupBox)
        self.hideReferenceCheckBox.setGeometry(QtCore.QRect(255, 20, 131, 21))
        self.hideReferenceCheckBox.setObjectName("hideReferenceCheckBox")
        self.deleteSnakeButton = QtGui.QPushButton(self.snakeGroupBox)
        self.deleteSnakeButton.setGeometry(QtCore.QRect(10, 20, 96, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteSnakeButton.sizePolicy().hasHeightForWidth())
        self.deleteSnakeButton.setSizePolicy(sizePolicy)
        self.deleteSnakeButton.setObjectName("deleteSnakeButton")
        self.loadSnakeButton = QtGui.QPushButton(self.snakeGroupBox)
        self.loadSnakeButton.setGeometry(QtCore.QRect(260, 70, 126, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSnakeButton.sizePolicy().hasHeightForWidth())
        self.loadSnakeButton.setSizePolicy(sizePolicy)
        self.loadSnakeButton.setObjectName("loadSnakeButton")
        self.saveSnakeButton = QtGui.QPushButton(self.snakeGroupBox)
        self.saveSnakeButton.setGeometry(QtCore.QRect(260, 45, 126, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSnakeButton.sizePolicy().hasHeightForWidth())
        self.saveSnakeButton.setSizePolicy(sizePolicy)
        self.saveSnakeButton.setObjectName("saveSnakeButton")
        self.exportGroupBox = QtGui.QGroupBox(self.snakeGroupBox)
        self.exportGroupBox.setGeometry(QtCore.QRect(220, 180, 161, 80))
        self.exportGroupBox.setObjectName("exportGroupBox")
        self.exportSVGButton = QtGui.QPushButton(self.exportGroupBox)
        self.exportSVGButton.setGeometry(QtCore.QRect(20, 25, 111, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportSVGButton.sizePolicy().hasHeightForWidth())
        self.exportSVGButton.setSizePolicy(sizePolicy)
        self.exportSVGButton.setObjectName("exportSVGButton")
        self.cursorGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.cursorGroupBox.setGeometry(QtCore.QRect(10, 660, 281, 81))
        self.cursorGroupBox.setFlat(False)
        self.cursorGroupBox.setCheckable(False)
        self.cursorGroupBox.setObjectName("cursorGroupBox")
        self.layoutWidget = QtGui.QWidget(self.cursorGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 20, 131, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.xPosLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPosLabel.sizePolicy().hasHeightForWidth())
        self.xPosLabel.setSizePolicy(sizePolicy)
        self.xPosLabel.setObjectName("xPosLabel")
        self.gridLayout.addWidget(self.xPosLabel, 0, 0, 1, 1)
        self.yPosLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPosLabel.sizePolicy().hasHeightForWidth())
        self.yPosLabel.setSizePolicy(sizePolicy)
        self.yPosLabel.setObjectName("yPosLabel")
        self.gridLayout.addWidget(self.yPosLabel, 0, 2, 1, 1)
        self.yPos = QtGui.QLabel(self.layoutWidget)
        self.yPos.setObjectName("yPos")
        self.gridLayout.addWidget(self.yPos, 0, 3, 1, 1)
        self.xPos = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPos.sizePolicy().hasHeightForWidth())
        self.xPos.setSizePolicy(sizePolicy)
        self.xPos.setObjectName("xPos")
        self.gridLayout.addWidget(self.xPos, 0, 1, 1, 1)
        self.cursorPositionLabel = QtGui.QLabel(self.cursorGroupBox)
        self.cursorPositionLabel.setGeometry(QtCore.QRect(10, 30, 61, 17))
        self.cursorPositionLabel.setObjectName("cursorPositionLabel")
        self.cursorExtEnergyLabel = QtGui.QLabel(self.cursorGroupBox)
        self.cursorExtEnergyLabel.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.cursorExtEnergyLabel.setObjectName("cursorExtEnergyLabel")
        self.cursorExtEnergyDisplayLabel = QtGui.QLabel(self.cursorGroupBox)
        self.cursorExtEnergyDisplayLabel.setGeometry(QtCore.QRect(120, 60, 121, 17))
        self.cursorExtEnergyDisplayLabel.setObjectName("cursorExtEnergyDisplayLabel")
        #-----------------------------------------------------------------------
        # self.qimageviewer = QImageViewer(self.centralwidget)
        # self.qimageviewer.setGeometry(QtCore.QRect(410, 10, 730, 730))
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.qimageviewer.sizePolicy().hasHeightForWidth())
        # self.qimageviewer.setSizePolicy(sizePolicy)
        # self.qimageviewer.setZoomLevel(0)
        # self.qimageviewer.setObjectName("qimageviewer")
        #-----------------------------------------------------------------------
        self.s57GroupBox = QtGui.QGroupBox(self.centralwidget)
        self.s57GroupBox.setGeometry(QtCore.QRect(10, 90, 391, 241))
        self.s57GroupBox.setObjectName("s57GroupBox")
        self.openS57Button = QtGui.QPushButton(self.s57GroupBox)
        self.openS57Button.setGeometry(QtCore.QRect(10, 20, 100, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openS57Button.sizePolicy().hasHeightForWidth())
        self.openS57Button.setSizePolicy(sizePolicy)
        self.openS57Button.setObjectName("openS57Button")
        self.s57FeatureComboBox = QtGui.QComboBox(self.s57GroupBox)
        self.s57FeatureComboBox.setGeometry(QtCore.QRect(10, 80, 91, 27))
        self.s57FeatureComboBox.setObjectName("s57FeatureComboBox")
        self.s57FieldComboBox = QtGui.QComboBox(self.s57GroupBox)
        self.s57FieldComboBox.setGeometry(QtCore.QRect(100, 80, 91, 27))
        self.s57FieldComboBox.setObjectName("s57FieldComboBox")
        self.s57ValueComboBox = QtGui.QComboBox(self.s57GroupBox)
        self.s57ValueComboBox.setGeometry(QtCore.QRect(190, 80, 91, 27))
        self.s57ValueComboBox.setObjectName("s57ValueComboBox")
        self.s57FileNameLabel = QtGui.QLabel(self.s57GroupBox)
        self.s57FileNameLabel.setGeometry(QtCore.QRect(110, 30, 281, 17))
        self.s57FileNameLabel.setObjectName("s57FileNameLabel")
        self.s57FileNameLabel_2 = QtGui.QLabel(self.s57GroupBox)
        self.s57FileNameLabel_2.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.s57FileNameLabel_2.setObjectName("s57FileNameLabel_2")
        self.s57FileNameLabel_3 = QtGui.QLabel(self.s57GroupBox)
        self.s57FileNameLabel_3.setGeometry(QtCore.QRect(100, 60, 81, 17))
        self.s57FileNameLabel_3.setObjectName("s57FileNameLabel_3")
        self.s57FileNameLabel_4 = QtGui.QLabel(self.s57GroupBox)
        self.s57FileNameLabel_4.setGeometry(QtCore.QRect(190, 60, 81, 17))
        self.s57FileNameLabel_4.setObjectName("s57FileNameLabel_4")
        self.removeFeatureButton = QtGui.QPushButton(self.s57GroupBox)
        self.removeFeatureButton.setGeometry(QtCore.QRect(310, 80, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeFeatureButton.sizePolicy().hasHeightForWidth())
        self.removeFeatureButton.setSizePolicy(sizePolicy)
        self.removeFeatureButton.setObjectName("removeFeatureButton")
        self.addFeatureButton = QtGui.QPushButton(self.s57GroupBox)
        self.addFeatureButton.setGeometry(QtCore.QRect(280, 80, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFeatureButton.sizePolicy().hasHeightForWidth())
        self.addFeatureButton.setSizePolicy(sizePolicy)
        self.addFeatureButton.setObjectName("addFeatureButton")
        self.clearFeatureListButton = QtGui.QPushButton(self.s57GroupBox)
        self.clearFeatureListButton.setGeometry(QtCore.QRect(340, 80, 41, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearFeatureListButton.sizePolicy().hasHeightForWidth())
        self.clearFeatureListButton.setSizePolicy(sizePolicy)
        self.clearFeatureListButton.setObjectName("clearFeatureListButton")
        self.featuresList = QtGui.QListWidget(self.s57GroupBox)
        self.featuresList.setGeometry(QtCore.QRect(100, 110, 281, 111))
        self.featuresList.setObjectName("featuresList")
        self.label = QtGui.QLabel(self.s57GroupBox)
        self.label.setGeometry(QtCore.QRect(100, 225, 256, 17))
        self.label.setObjectName("label")
        self.filterFeaturesByVisButton = QtGui.QPushButton(self.s57GroupBox)
        self.filterFeaturesByVisButton.setGeometry(QtCore.QRect(10, 110, 91, 26))
        self.filterFeaturesByVisButton.setObjectName("filterFeaturesByVisButton")
        self.addAllFeaturesButton = QtGui.QPushButton(self.s57GroupBox)
        self.addAllFeaturesButton.setGeometry(QtCore.QRect(10, 135, 91, 26))
        self.addAllFeaturesButton.setObjectName("addAllFeaturesButton")
        self.hideAllFeaturesButton = QtGui.QPushButton(self.s57GroupBox)
        self.hideAllFeaturesButton.setGeometry(QtCore.QRect(10, 195, 91, 26))
        self.hideAllFeaturesButton.setObjectName("hideAllFeaturesButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SnakeIsland", None, QtGui.QApplication.UnicodeUTF8))
        self.imageGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.openImageButton.setText(QtGui.QApplication.translate("MainWindow", "Open Image", None, QtGui.QApplication.UnicodeUTF8))
        self.imageNameLabel.setText(QtGui.QApplication.translate("MainWindow", " imageFileName", None, QtGui.QApplication.UnicodeUTF8))
        self.brightnessLabel.setText(QtGui.QApplication.translate("MainWindow", "Brightness", None, QtGui.QApplication.UnicodeUTF8))
        self.brightnessValueLabel.setText(QtGui.QApplication.translate("MainWindow", "brgn value", None, QtGui.QApplication.UnicodeUTF8))
        self.snakeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.resetSnakeButton.setText(QtGui.QApplication.translate("MainWindow", "Reset Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.energyGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Energies", None, QtGui.QApplication.UnicodeUTF8))
        self.internalEnergyLabel.setText(QtGui.QApplication.translate("MainWindow", "Internal", None, QtGui.QApplication.UnicodeUTF8))
        self.spacingLabel.setText(QtGui.QApplication.translate("MainWindow", "Spacing:", None, QtGui.QApplication.UnicodeUTF8))
        self.curvatureLabel.setText(QtGui.QApplication.translate("MainWindow", "Curvature:", None, QtGui.QApplication.UnicodeUTF8))
        self.goalLengthEdit.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.goalLengthLabel.setText(QtGui.QApplication.translate("MainWindow", "Goal length:", None, QtGui.QApplication.UnicodeUTF8))
        self.externalEnergyLabel.setText(QtGui.QApplication.translate("MainWindow", "External", None, QtGui.QApplication.UnicodeUTF8))
        self.spacingDisplayLabel.setText(QtGui.QApplication.translate("MainWindow", "spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.curvatureDisplayLabel.setText(QtGui.QApplication.translate("MainWindow", "curvature", None, QtGui.QApplication.UnicodeUTF8))
        self.gradMagnDisplayLabel.setText(QtGui.QApplication.translate("MainWindow", "gradmagn", None, QtGui.QApplication.UnicodeUTF8))
        self.externalMaxLabel.setText(QtGui.QApplication.translate("MainWindow", "max:", None, QtGui.QApplication.UnicodeUTF8))
        self.externalMaxDisplayLabel.setText(QtGui.QApplication.translate("MainWindow", "maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.innerWeightEdit.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.outerWeightEdit.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.flipNormalsButton.setText(QtGui.QApplication.translate("MainWindow", "flip Normals", None, QtGui.QApplication.UnicodeUTF8))
        self.snakeFromS57CheckBox.setText(QtGui.QApplication.translate("MainWindow", "Snake from S57", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Optimization", None, QtGui.QApplication.UnicodeUTF8))
        self.optimizationStepsLabel.setText(QtGui.QApplication.translate("MainWindow", "Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.optimizationStepsEdit.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.optimizeButton.setText(QtGui.QApplication.translate("MainWindow", "Optimize", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedStepSizeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "fixed step size", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedStepSizeEdit.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.resetMapSamplesButton.setText(QtGui.QApplication.translate("MainWindow", "Reset Map Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.reSampleS57Button.setText(QtGui.QApplication.translate("MainWindow", "(Re)Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.hideReferenceCheckBox.setText(QtGui.QApplication.translate("MainWindow", "hide \'reference\'", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSnakeButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSnakeButton.setText(QtGui.QApplication.translate("MainWindow", "load Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSnakeButton.setText(QtGui.QApplication.translate("MainWindow", "save Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.exportGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.exportSVGButton.setText(QtGui.QApplication.translate("MainWindow", "Export as SVG", None, QtGui.QApplication.UnicodeUTF8))
        self.cursorGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Cursor", None, QtGui.QApplication.UnicodeUTF8))
        self.xPosLabel.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.yPosLabel.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.yPos.setText(QtGui.QApplication.translate("MainWindow", "yPos", None, QtGui.QApplication.UnicodeUTF8))
        self.xPos.setText(QtGui.QApplication.translate("MainWindow", "xPos", None, QtGui.QApplication.UnicodeUTF8))
        self.cursorPositionLabel.setText(QtGui.QApplication.translate("MainWindow", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.cursorExtEnergyLabel.setText(QtGui.QApplication.translate("MainWindow", "Ext-Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.cursorExtEnergyDisplayLabel.setText(QtGui.QApplication.translate("MainWindow", "cursorExtEnergy", None, QtGui.QApplication.UnicodeUTF8))
        self.s57GroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "S57", None, QtGui.QApplication.UnicodeUTF8))
        self.openS57Button.setText(QtGui.QApplication.translate("MainWindow", "Open ENC", None, QtGui.QApplication.UnicodeUTF8))
        self.s57FileNameLabel.setText(QtGui.QApplication.translate("MainWindow", " s57FileName", None, QtGui.QApplication.UnicodeUTF8))
        self.s57FileNameLabel_2.setText(QtGui.QApplication.translate("MainWindow", " Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.s57FileNameLabel_3.setText(QtGui.QApplication.translate("MainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.s57FileNameLabel_4.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFeatureButton.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.addFeatureButton.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.clearFeatureListButton.setText(QtGui.QApplication.translate("MainWindow", "clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "(double-click list item to adjust colour)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterFeaturesByVisButton.setText(QtGui.QApplication.translate("MainWindow", "filter by vis.", None, QtGui.QApplication.UnicodeUTF8))
        self.addAllFeaturesButton.setText(QtGui.QApplication.translate("MainWindow", "add all", None, QtGui.QApplication.UnicodeUTF8))
        self.hideAllFeaturesButton.setText(QtGui.QApplication.translate("MainWindow", "hide all", None, QtGui.QApplication.UnicodeUTF8))

#from VigraQt.qimageviewer.hxx import QImageViewer
